### ISSUE TITLE
Undefined constant "top"

### ISSUE THREAD

**Issue by pixsolution** [koossaayy/laravel-mapbox#13]
Hello, I've installed your package, the normal component <x-mapbox id="mapId" /> works well, but when I try to use the option with search it gives me the following error attached capture
![1](https://github.com/koossaayy/laravel-mapbox/assets/47191848/821fc394-2197-4299-926d-8c708f659f9f)
![2](https://github.com/koossaayy/laravel-mapbox/assets/47191848/2f00e251-2302-4405-b812-e45a7444b2c0)

what can be?
I'm using laravel 9.19

**Comment by koossaayy** [comment]
It seems it was a mistake in the documentation, 
Instead of 
```
<x-mapbox-search 
        id="mapId" 
        placeholder="Search" 
        :center="[14, 17]" 
        :zoom="2" 
        :navigationControls="true"
        :geocoderPosition="top-left"
        :rtl="true"
        :cooperativeGestures="true"
    />
```

You can do 
```
<x-mapbox-search 
        id="mapId" 
        placeholder="Search" 
        :center="[14, 17]" 
        :zoom="2" 
        :navigationControls="true"
        geocoderPosition="top-left"
        :rtl="true"
        :cooperativeGestures="true"
    />

```
Which is basically remove the colons `:` from the `geocoderPosition` parameter. 
I will update the documentation now, and you can check if this solution worked for you or not. 
Thank you

**Comment by pixsolution** [comment]
it work thanks!
