### ISSUE TITLE
Component is placed on top of all elements of the view

### ISSUE THREAD

**Issue by pixsolution** [koossaayy/laravel-mapbox#15]
Hello, sorry for asking this question here, which is for bugs, but I chose the "Ask question" option and it leads me to a 404 attached screenshot. 
![2](https://github.com/koossaayy/laravel-mapbox/assets/47191848/578a3bec-ab2f-4124-adc5-5ccf32209253)
I wanted to ask why the component is placed on top of all elements of the view attached captures:
![1](https://github.com/koossaayy/laravel-mapbox/assets/47191848/56211b85-eec9-4a98-9997-7fff2fe7042e)
![3](https://github.com/koossaayy/laravel-mapbox/assets/47191848/413e64b9-8070-479d-8862-fa556d3473b3)
If you see the code capture, I comment the code where I had the google maps before, which looked good below the fields, but when I put the mapbox it is placed on top of everything. And I've already tried in other views...
I am using TALL stack
Why can be?

Regards

**Comment by pixsolution** [comment]
I think it's because of that property
![1](https://github.com/koossaayy/laravel-mapbox/assets/47191848/5e17c0c6-a99e-4778-9e78-a97c1d9ecb1a)
 but I've tried with all the types https://www.w3schools.com/css/css_positioning.asp and I can't solve it, and if I remove it it disappears the map, I just want it to respect the div so I can place it where I want

**Comment by koossaayy** [comment]
Hello, sorry for the late, it's a holiday here. 
The problem you're having, since the component is positioned absolute, you need to set the parent to relative. It will be positioned as the parent element. 
As the image shows : 
![image](https://github.com/koossaayy/laravel-mapbox/assets/6431084/14a33ac2-dc10-47c2-a09d-1d0f3ad70c06)

```html
            <div class="relative h-1/2">
                <x-mapbox-search id="mapId" placeholder="Search" :center="[14, 17]" :zoom="2" :navigationControls="true" geocoderPosition="top-left" :rtl="true" :cooperativeGestures="true" />
            </div>

```

**Comment by koossaayy** [comment]
@pixsolution I hope this solution worked for you, I will close this issue for now. 
If you have any other issues, feel free to open new ones. 
Thank you for using Laravel Mapbox ♥

**Comment by gabzon** [comment]
Hi @koossaayy, 
I have the same problem and adding 'relative' to the parent div did not work unfortunately

**Comment by koossaayy** [comment]
@gabzon Hello 
May I see a screenshot of the problem ? and your code snippets ?

**Comment by koossaayy** [comment]
I will check it again, and I'll try your layout and see.

**Comment by koossaayy** [comment]
@gabzon Indeed if you put it set it to relative in your situation it will work. 
I will submit a PR later that makes you change the position of the map, either relative or absolute. 
Thank you

**Comment by gabzon** [comment]
Super thanks @koossaayy

**Comment by koossaayy** [comment]
@gabzon 
Good afternon, please update to the latest version `0.4.3` , and you can use the position as a param.
Have a good day.
