### ISSUE TITLE
Multiple Maps on Single Page Do Not Render (Only First Map Renders

### ISSUE THREAD

**Issue by awizemann** [koossaayy/laravel-mapbox#24]
I am trying to get multiple maps to render on a single page for a gird view of multiple locations. I have tested multiple times with unique IDs and other methods. This issue is reproducible with the following code:

`<div class="">
        <div class="w-48">
            1<x-mapbox id="map1" class="rounded-t-lg h-36 w-36" position="relative" />
        </div>
        <div class="w-48">
            2 <x-mapbox id="map2" class="rounded-t-lg h-36 w-36" position="relative" />
        </div>
        <div class="w-48">
            3 <x-mapbox id="map3" class="rounded-t-lg h-36 w-36" position="relative" />
        </div>
    </div>
`

Any suggestions to get this to work?

**Comment by koossaayy** [comment]
Hello, 
Probably because of the `map` constant in the script. 
I will open a PR to fix this issue. 
Thank you.

**Comment by awizemann** [comment]
Thank you, worked like a charm.
